version: '3.8'            

services:
  server:
    image: server
    build:
      context: ./backend/
    ports:
      - 3001:3001
    container_name: backend

  app:
    image: frontend
    build:
      context: ./frontend/
    ports:
      - 3210:3000
    container_name: frontend

  
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy

